# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

history:
  exclude:
    domains:
      - sun
      - group
      - script
      - climate
      - automation
      - input_text
      - input_select
      - input_boolean

sun:
  hidden: true

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

modbus:
  type: rtuovertcp
  host: 10.10.0.139
  port: 502

climate:
  - platform: modbus2
    name: [客厅空调, 主卧空调, 次卧空调, 书房空调]
    fan_mode: { registers: [6, 10, 14, 18] }
    fan_modes: { auto: 0, 一级: 1, 二级: 2, 三级: 3, 四级: 4, 五级: 5 }
    hvac_mode: { registers: [5, 9, 13, 17] }
    hvac_modes: { "off": 0, cool: 1, heat: 2, dry: 3, fan_only: 4 }
    hvac_off: { registers: [1, 2, 3, 4], register_type: coil }
    target_temperature: { registers: [4, 8, 12, 16] }
    temperature: { registers: [3, 6, 9, 12], register_type: input, scale: 0.1 }

fan:
  - platform: xiaomi_miio
    name: Xiaomi Air Purifier 2
    host: 10.10.0.181
    token: !secret purifier_token
    model: zhimi.airpurifier.m2

yeelight:
  devices:
    10.10.0.212:
      name: 客厅灯
      save_on_change: False
    10.10.0.146:
      name: 主卧灯
      save_on_change: False
    10.10.0.152:
      name: 书房灯
      save_on_change: False
    10.10.0.131:
      name: 餐厅灯
      save_on_change: False
    10.10.0.157:
      name: 次卧灯
      save_on_change: False

remote:
  - platform: xiaomi_miio
    host: 10.10.0.199
    token: !secret ir_token
    name: "IR remote"
    slot: 1
    timeout: 30
    hidden: false
